### ISSUE TITLE
Add support for context specific types

### ISSUE THREAD

**Issue by huysentruitw** [huysentruitw/pem-utils#16]
See https://github.com/huysentruitw/pem-utils/pull/9

**Comment by huysentruitw** [comment]
From https://docs.ldap.com/ldap-sdk/docs/ldap-wire-protocol-reference/asn1-ber.html, http://luca.ntop.org/Teaching/Appunti/asn1.html and others, I've learned that the current implemented ASN.1 types (Boolean, Integer, Null, etc) are only valid within the _universal_ class range and not for the _application_ or _context-specific_ class, where the tag identifier has a different meaning.

Will probably have to refactor the `DerAsnType` base class and additionally add the possibility to register class-specific parsers.

cc @qmfrederik

**Comment by huysentruitw** [comment]
Refactor finished (v3.0)

**Comment by cleftheris** [comment]
Hi and thanks for your efforts. Is there an example for how todo this?
I have case where I am creating a `DerAsnIa5String` and serializes perfectly!
```csharp
var contextSpesificId = new DerAsnIdentifier(DerAsnTagClass.ContextSpecific, DerAsnEncodingType.Primitive, DerAsnKnownTypeTags.Primitive.ObjectIdentifier);
var location = new DerAsnIa5String(contextSpesificId, uri.ToString());
// etc....
```
But cant seem to get the value out. I tried to hack my way through by doing `Encoding.ASCII.GetString(objectIdentifier.Value.Select(x => (byte)x).ToArray())` which gives me almost the string I wanted with missing one character plus two control characters at the begining. Did not like this approach anyway.

What i am trying to figure out is how to tell the default decoder not to parse this into `DerAsnObjectIdentifier` if it sees the `DerAsnTagClass.ContextSpecific` but instead parse it into `DerAsnIa5String`. Can it be done?
