### ISSUE TITLE
Decoding indefinite-length encoded values

### ISSUE THREAD

**Issue by qmfrederik** [huysentruitw/pem-utils#18]
Consider e.g. the following value:

```
30 80 a0 80 80 01 06 83 02 00 e2 00 00 a2 80 80 01 01 81 01 0d 00 00 83 01 65 00 00
```

This [decodes to](https://lapo.it/asn1js/#3080A080800106830200E20000A28080010181010D00008301650000) 

```
SEQUENCE(3 elem)
  [0](2 elem)
    [0](1 byte) 06
    [3](2 byte) 00E2
  [2](2 elem)
    [0](1 byte) 01
    [1](1 byte) 0D
  [3]e
```

This uses indefinite-length encoding (see [paragraph 8.1.3.6](https://www.itu.int/ITU-T/studygroups/com17/languages/X.690-0207.pdf)), which is currently not supported.

**Comment by huysentruitw** [comment]
Seems like indefinite-length is not supported in DER (subset of BER). Also the [MSDN docs about DER/ASN.1] (https://docs.microsoft.com/en-us/windows/desktop/seccertenroll/about-encoded-length-and-value-bytes) don't talk about indefinite-length.

See section 4 in http://luca.ntop.org/Teaching/Appunti/asn1.html
