### ISSUE TITLE
Any Plans to support .net core?

### ISSUE THREAD

**Issue by DSUK** [huysentruitw/pem-utils#2]

**Comment by huysentruitw** [comment]
The build uses VS2017, so it is technically possible to support both .NET Framework and .NET Core. I currently have no time for this, if you have time, you're free to send a PR.

A starting point would be https://docs.microsoft.com/en-us/dotnet/core/porting/project-structure

**Comment by huysentruitw** [comment]
@DSUK I've published package 1.0.0.18 on NuGet which supports both net452 and netstandard1.5

Can you test this package in a .NET Core project and give me feedback? Thank you!

**Comment by DSUK** [comment]
Hi, Thanks for doing this 👍 ,

The source itself works great if I manually add it to a project.

but the package when I install it via Nuget will throw an error.

> Install-Package : Package DerConverter 1.0.0.4 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package DerConverter 1.0.0.4 
supports: net452 (.NETFramework,Version=v4.5.2)

**Comment by huysentruitw** [comment]
Hi, that version certainly won't work 😉 
Can you try with the latest package version, should be 1.0.0.18

**Comment by huysentruitw** [comment]
Closing this as I have the feeling that you have this resolved by now. If not, feel free to re-open! Cheers!

**Comment by DSUK** [comment]
Sorry, forgot to reply
I did manage to get this working :).
